# application.yml
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: library-management-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: library_user
    password: library123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.library: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  
  h2:
    console:
      enabled: true

jwt:
  secret: testSecretKey123456789012345678901234567890
  expiration: 3600000 # 1 hour for testsnpx expo start --clear